name: CI/CD Pipeline

env:
  CI: false

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 'stable'

    - name: Install Dependencies
      run: npm install

    - name: Start Node Server
      run: npm start

    # Add any tests or other steps here

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.EC2_PORT }}
        script: |
          cd /home/ec2-user/Lunova/
          git pull
          npm install --production
          npx pm2 restart all
